version: 0.2
phases:
  pre_build:      
    commands:
      - node -v
      - cd angular-ccp
  build:
    commands:      
      - npm install 
      - npm run build:prod
      - cd ..
  post_build:
    commands:      
      - aws s3 sync angular-ccp/dist/angular-ccp "s3://${BUCKET_NAME}/" --acl bucket-owner-full-control --acl public-read --delete --cache-control "max-age=86400" --exclude angular-ccp/dist/angular-ccp/assets
      - aws s3 sync angular-ccp/dist/angular-ccp/assets "s3://${BUCKET_NAME}/assets" --acl bucket-owner-full-control --acl public-read --delete --cache-control "max-age=31536000"
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"